### ISSUE TITLE
大哥，能说下怎么用嘛？

### ISSUE THREAD

**Issue by LouisMari1991** [xbotao/hexo-admin-qiniu#4]
为嘛我复制粘贴不行呢？

**Comment by xbotao** [comment]
请参考  https://xbotao.github.io/hexo-admin-qiniu/
还有，一定要使用一定要注意 “华东区”

**Comment by LouisMari1991** [comment]
嗨呀,刚看到你的回复呀，我后面用别的插件解决了我的问题：https://github.com/knightli/qiniu-uploader,
我使用插件的踩坑过程: https://marishunxiang.github.io/
